***Задача 1***

In [ ]:
import numpy as np

In [ ]:
a = np.matrix([[1,2,1],[-2,1,1]])
b = np.matrix([[3,1],[1,0],[2,4]])
c = np.matrix([[-2,2],[1,-1],[1,2]])

А+2B

In [ ]:
try:
  print(a+2*b)
except:
  try:
    print(2+np.transpose(2*b))
  except(Exception) as e:
    print(str(e))

[[ 8  4  6]
 [ 4  2 10]]


B+2C

In [ ]:
try:
  print(b+2*c)
except:
  try:
    print(b+np.transpose(2*c))
  except(Exception) as e:
    print(str(e))

[[-1  5]
 [ 3 -2]
 [ 4  8]]


***Задача 2***

In [ ]:
r = np.zeros(shape = (8, 8), dtype=int)
r

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
r[1::2,::2] = 1
r[::2,1::2] = 1
r

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

***Задача 3***

In [ ]:
x = np.arange(0,1.5,0.1)
y = np.arange(1,7)
print(x)
print(y)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1 2 3 4 5 6]


In [ ]:
x1 = x.reshape(5,3)
x1

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8],
       [0.9, 1. , 1.1],
       [1.2, 1.3, 1.4]])

In [ ]:
y1=y.reshape(3,2)
y1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
res = np.matmul(x1, y1)
res

array([[ 1.3,  1.6],
       [ 4. ,  5.2],
       [ 6.7,  8.8],
       [ 9.4, 12.4],
       [12.1, 16. ]])

***Задача 4***

In [ ]:
q = np.arange(start=1, step = 2, stop = 73, dtype='int32')
q

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71], dtype=int32)

In [ ]:
newArr = q[q % 3 == 0]
newArr

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69], dtype=int32)